// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0FrMhgEH505UblBKd4s_QvsC-kqNilQw',
    appId: '1:854147530887:web:923dbb1e553c8230d27822',
    messagingSenderId: '854147530887',
    projectId: 'miage-20241017',
    authDomain: 'miage-20241017.firebaseapp.com',
    storageBucket: 'miage-20241017.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjk46Hqng9OA2AZiVLW58R1NwiyoahE7E',
    appId: '1:854147530887:android:e71a162add8afda1d27822',
    messagingSenderId: '854147530887',
    projectId: 'miage-20241017',
    storageBucket: 'miage-20241017.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVKKwzAHsK5Z8J-xY_g1N7JF0ssmXYMQE',
    appId: '1:854147530887:ios:cae96cab0e30d033d27822',
    messagingSenderId: '854147530887',
    projectId: 'miage-20241017',
    storageBucket: 'miage-20241017.appspot.com',
    iosBundleId: 'com.example.flutterApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVKKwzAHsK5Z8J-xY_g1N7JF0ssmXYMQE',
    appId: '1:854147530887:ios:cae96cab0e30d033d27822',
    messagingSenderId: '854147530887',
    projectId: 'miage-20241017',
    storageBucket: 'miage-20241017.appspot.com',
    iosBundleId: 'com.example.flutterApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0FrMhgEH505UblBKd4s_QvsC-kqNilQw',
    appId: '1:854147530887:web:820dbba534227960d27822',
    messagingSenderId: '854147530887',
    projectId: 'miage-20241017',
    authDomain: 'miage-20241017.firebaseapp.com',
    storageBucket: 'miage-20241017.appspot.com',
  );
}
